language: cpp
sudo: required
# dist: xenial
osx_image: xcode11.3
compiler:
#   - gcc
  - clang
os:
#   - linux
    - osx
install:
before_script:
  - sudo -l
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - current_path=$(cd "$(dirname $0)";pwd)
  - export PATH=${PATH}:${current_path}
  - vcpkg install cpp-netlib
  - vcpkg install gtest
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  - cmake ..
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  # once CMake has done its job we just build using make as usual
  - sudo make
  # if the project uses ctest we can run the tests like this
  # - make test
